@DotnetNiger.Community_HostAddress = https://localhost:7269

GET {{DotnetNiger.Community_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{DotnetNiger.Community_HostAddress}}/api/team/couranDaga

###
