export const identityEndpoints = [
  {
    group: "Diagnostics & Tests",
    items: [
      {
        id: "diagnostics-ping",
        label: "Diagnostics · Ping",
        method: "GET",
        path: "/api/v{version}/diagnostics/ping",
        description: "Retourne un indicateur simple de disponibilité.",
        auth: "public",
        bodyMode: "none",
      },
      {
        id: "diagnostics-health",
        label: "Diagnostics · Health",
        method: "GET",
        path: "/api/v{version}/diagnostics/health",
        description: "Expose l'état interne de l'API.",
        auth: "public",
        bodyMode: "none",
      },
      {
        id: "test-get",
        label: "Test · Liste",
        method: "GET",
        path: "/api/v{version}/test",
        description: "Endpoint de test générique.",
        auth: "public",
        bodyMode: "none",
      },
      {
        id: "test-health",
        label: "Test · Health",
        method: "GET",
        path: "/api/v{version}/health",
        description: "Alternative simple pour vérifier le service.",
        auth: "public",
        bodyMode: "none",
      },
    ],
  },
  {
    group: "Authentification",
    items: [
      {
        id: "auth-register",
        label: "Register",
        method: "POST",
        path: "/api/v{version}/auth/register",
        description: "Crée un compte utilisateur.",
        auth: "public",
        bodyMode: "json",
        body: {
          username: "devuser",
          email: "dev@example.com",
          password: "Passw0rd!",
          fullName: "Dev User",
          country: "Niger",
          city: "Niamey",
        },
      },
      {
        id: "auth-login",
        label: "Login",
        method: "POST",
        path: "/api/v{version}/auth/login",
        description: "Obtient un access token + refresh token.",
        auth: "public",
        bodyMode: "json",
        body: {
          email: "dev@example.com",
          password: "Passw0rd!",
          rememberMe: true,
        },
      },
      {
        id: "auth-forgot",
        label: "Mot de passe oublié",
        method: "POST",
        path: "/api/v{version}/auth/forgot-password",
        description: "Déclenche la génération d'un token de réinitialisation.",
        auth: "public",
        bodyMode: "json",
        body: {
          email: "dev@example.com",
        },
      },
      {
        id: "auth-request-email",
        label: "Demander vérification email",
        method: "POST",
        path: "/api/v{version}/auth/request-email-verification",
        description: "Renvoie un email de confirmation.",
        auth: "public",
        bodyMode: "json",
        body: {
          email: "dev@example.com",
        },
      },
      {
        id: "auth-reset-password",
        label: "Reset password",
        method: "POST",
        path: "/api/v{version}/auth/reset-password",
        description: "Réinitialise un mot de passe via le token reçu.",
        auth: "public",
        bodyMode: "json",
        body: {
          email: "dev@example.com",
          token: "<copiez-le dep. email>",
          newPassword: "NewPassw0rd!",
        },
      },
      {
        id: "auth-verify-email",
        label: "Vérifier email",
        method: "POST",
        path: "/api/v{version}/auth/verify-email",
        description: "Valide un email via le token envoyé.",
        auth: "public",
        bodyMode: "json",
        body: {
          email: "dev@example.com",
          token: "<token>",
        },
      },
    ],
  },
  {
    group: "Tokens",
    items: [
      {
        id: "tokens-refresh",
        label: "Rafraîchir token",
        method: "POST",
        path: "/api/v{version}/tokens/refresh",
        description: "Renvoie un nouvel access token à partir du refresh token.",
        auth: "public",
        bodyMode: "json",
        body: {
          refreshToken: "{{refreshToken}}",
        },
      },
      {
        id: "tokens-logout",
        label: "Logout",
        method: "POST",
        path: "/api/v{version}/tokens/logout",
        description: "Révoque un refresh token pour l'utilisateur courant.",
        auth: "user",
        bodyMode: "json",
        body: {
          refreshToken: "{{refreshToken}}",
        },
      },
    ],
  },
  {
    group: "Profil utilisateur",
    items: [
      {
        id: "users-me",
        label: "Profil · GET",
        method: "GET",
        path: "/api/v{version}/users/me",
        description: "Retourne le profil de l'utilisateur connecté.",
        auth: "user",
        bodyMode: "none",
      },
      {
        id: "users-update",
        label: "Profil · PUT",
        method: "PUT",
        path: "/api/v{version}/users/me",
        description: "Met à jour les informations du profil.",
        auth: "user",
        bodyMode: "json",
        body: {
          fullName: "Dev User",
          bio: "Community builder",
          avatarUrl: "",
          country: "Niger",
          city: "Niamey",
        },
      },
      {
        id: "users-avatar-info",
        label: "Avatar · GET metadata",
        method: "GET",
        path: "/api/v{version}/users/me/avatar",
        description: "Retourne les métadonnées de l'avatar courant.",
        auth: "user",
        bodyMode: "none",
      },
      {
        id: "users-change-password",
        label: "Changer mot de passe",
        method: "POST",
        path: "/api/v{version}/users/me/change-password",
        description: "Remplace le mot de passe via l'ancien.",
        auth: "user",
        bodyMode: "json",
        body: {
          currentPassword: "Passw0rd!",
          newPassword: "NouveauPassw0rd!",
        },
      },
      {
        id: "users-change-email",
        label: "Changer email",
        method: "POST",
        path: "/api/v{version}/users/me/change-email",
        description: "Change l'adresse email après vérification du mot de passe.",
        auth: "user",
        bodyMode: "json",
        body: {
          newEmail: "nouvel.email@example.com",
          currentPassword: "Passw0rd!",
        },
      },
      {
        id: "users-upload-avatar",
        label: "Uploader avatar",
        method: "POST",
        path: "/api/v{version}/users/me/avatar",
        description: "Télécharge un nouvel avatar (image PNG, JPG, WEBP).",
        auth: "user",
        bodyMode: "file",
        fileField: "avatar",
        fileHint: "Fichier image · max selon configuration appsettings.",
      },
      {
        id: "users-delete-avatar",
        label: "Supprimer avatar",
        method: "DELETE",
        path: "/api/v{version}/users/me/avatar",
        description: "Efface l'avatar et remet le profil par défaut.",
        auth: "user",
        bodyMode: "none",
      },
    ],
  },
  {
    group: "Liens sociaux",
    items: [
      {
        id: "social-list",
        label: "Lister mes liens",
        method: "GET",
        path: "/api/v{version}/social-links",
        description: "Retourne tous les liens sociaux liés au compte.",
        auth: "user",
        bodyMode: "none",
      },
      {
        id: "social-add",
        label: "Ajouter un lien",
        method: "POST",
        path: "/api/v{version}/social-links",
        description: "Crée un lien social (GitHub, Twitter, etc.).",
        auth: "user",
        bodyMode: "json",
        body: {
          platform: "GitHub",
          url: "https://github.com/dotnetniger",
        },
      },
      {
        id: "social-delete",
        label: "Supprimer un lien",
        method: "DELETE",
        path: "/api/v{version}/social-links/{linkId}",
        description: "Supprime le lien social ciblé.",
        auth: "user",
        pathParams: [
          { key: "linkId", label: "Guid du lien", sample: "00000000-0000-0000-0000-000000000000" },
        ],
        bodyMode: "none",
      },
    ],
  },
  {
    group: "Clés API personnelles",
    items: [
      {
        id: "apikey-list",
        label: "Lister mes clés",
        method: "GET",
        path: "/api/v{version}/api-keys",
        description: "Retourne toutes les clés API de l'utilisateur.",
        auth: "user",
        bodyMode: "none",
      },
      {
        id: "apikey-create",
        label: "Créer une clé",
        method: "POST",
        path: "/api/v{version}/api-keys",
        description: "Génère une clé API et retourne le secret.",
        auth: "user",
        bodyMode: "json",
        body: {
          name: "Integration CLI",
          expiresAt: "2025-12-31T23:59:59Z",
        },
      },
      {
        id: "apikey-rotate",
        label: "Rotater une clé",
        method: "POST",
        path: "/api/v{version}/api-keys/{apiKeyId}/rotate",
        description: "Régénère le secret d'une clé spécifique.",
        auth: "user",
        pathParams: [
          {
            key: "apiKeyId",
            label: "Guid de la clé",
            sample: "00000000-0000-0000-0000-000000000000",
          },
        ],
        bodyMode: "none",
      },
      {
        id: "apikey-revoke",
        label: "Révoquer une clé",
        method: "DELETE",
        path: "/api/v{version}/api-keys/{apiKeyId}",
        description: "Révoque définitivement la clé.",
        auth: "user",
        pathParams: [
          {
            key: "apiKeyId",
            label: "Guid de la clé",
            sample: "00000000-0000-0000-0000-000000000000",
          },
        ],
        bodyMode: "none",
      },
      {
        id: "apikey-revoke-all",
        label: "Révoquer toutes les clés",
        method: "POST",
        path: "/api/v{version}/api-keys/revoke-all",
        description: "Révoque toutes les clés liées à l'utilisateur courant.",
        auth: "user",
        bodyMode: "none",
      },
    ],
  },
  {
    group: "Gestion des rôles",
    items: [
      {
        id: "roles-list",
        label: "Lister les rôles",
        method: "GET",
        path: "/api/v{version}/roles",
        description: "Retourne tous les rôles disponibles.",
        auth: "admin",
        bodyMode: "none",
      },
      {
        id: "roles-create",
        label: "Créer un rôle",
        method: "POST",
        path: "/api/v{version}/roles",
        description: "Ajoute un rôle nommé.",
        auth: "admin",
        bodyMode: "json",
        body: {
          name: "CommunityModerator",
        },
      },
      {
        id: "roles-delete",
        label: "Supprimer un rôle",
        method: "DELETE",
        path: "/api/v{version}/roles/{roleId}",
        description: "Efface le rôle ciblé (GUID).",
        auth: "admin",
        pathParams: [
          { key: "roleId", label: "Guid du rôle", sample: "00000000-0000-0000-0000-000000000000" },
        ],
        bodyMode: "none",
      },
      {
        id: "roles-assign",
        label: "Assigner un rôle",
        method: "POST",
        path: "/api/v{version}/roles/assign",
        description: "Associe un rôle à un utilisateur.",
        auth: "admin",
        bodyMode: "json",
        body: {
          userId: "00000000-0000-0000-0000-000000000000",
          roleName: "Admin",
        },
      },
      {
        id: "roles-remove",
        label: "Retirer un rôle",
        method: "POST",
        path: "/api/v{version}/roles/remove",
        description: "Retire un rôle de l'utilisateur.",
        auth: "admin",
        bodyMode: "json",
        body: {
          userId: "00000000-0000-0000-0000-000000000000",
          roleName: "Admin",
        },
      },
      {
        id: "roles-user",
        label: "Rôles d'un user",
        method: "GET",
        path: "/api/v{version}/roles/user/{userId}",
        description: "Liste les rôles attribués à l'utilisateur spécifié.",
        auth: "admin",
        pathParams: [
          {
            key: "userId",
            label: "Guid utilisateur",
            sample: "00000000-0000-0000-0000-000000000000",
          },
        ],
        bodyMode: "none",
      },
    ],
  },
  {
    group: "Gestion des permissions",
    items: [
      {
        id: "permissions-list",
        label: "Lister les permissions",
        method: "GET",
        path: "/api/v{version}/permissions",
        description: "Retourne le catalogue des permissions.",
        auth: "admin",
        bodyMode: "none",
      },
      {
        id: "permissions-create",
        label: "Créer une permission",
        method: "POST",
        path: "/api/v{version}/permissions",
        description: "Ajoute une permission nommée.",
        auth: "admin",
        bodyMode: "json",
        body: {
          name: "users.export",
          description: "Autorise l'export des utilisateurs",
        },
      },
      {
        id: "permissions-delete",
        label: "Supprimer une permission",
        method: "DELETE",
        path: "/api/v{version}/permissions/{permissionId}",
        description: "Efface la permission ciblée.",
        auth: "admin",
        pathParams: [
          {
            key: "permissionId",
            label: "Guid permission",
            sample: "00000000-0000-0000-0000-000000000000",
          },
        ],
        bodyMode: "none",
      },
      {
        id: "permissions-assign",
        label: "Assigner une permission",
        method: "POST",
        path: "/api/v{version}/permissions/assign",
        description: "Associe une permission à un rôle.",
        auth: "admin",
        bodyMode: "json",
        body: {
          roleId: "00000000-0000-0000-0000-000000000000",
          permissionId: "00000000-0000-0000-0000-000000000000",
        },
      },
      {
        id: "permissions-remove",
        label: "Retirer une permission",
        method: "POST",
        path: "/api/v{version}/permissions/remove",
        description: "Retire la permission d'un rôle.",
        auth: "admin",
        bodyMode: "json",
        body: {
          roleId: "00000000-0000-0000-0000-000000000000",
          permissionId: "00000000-0000-0000-0000-000000000000",
        },
      },
      {
        id: "permissions-role",
        label: "Permissions d'un rôle",
        method: "GET",
        path: "/api/v{version}/permissions/role/{roleId}",
        description: "Liste les permissions attachées à un rôle.",
        auth: "admin",
        pathParams: [
          { key: "roleId", label: "Guid rôle", sample: "00000000-0000-0000-0000-000000000000" },
        ],
        bodyMode: "none",
      },
    ],
  },
  {
    group: "Administration",
    items: [
      {
        id: "admin-users",
        label: "Lister les utilisateurs",
        method: "GET",
        path: "/api/v{version}/admin/users",
        description: "Filtre et trie les utilisateurs (skip/take).",
        auth: "admin",
        query: {
          search: "",
          role: "",
          isActive: "",
          emailConfirmed: "",
          skip: 0,
          take: 20,
        },
        bodyMode: "none",
      },
      {
        id: "admin-user-detail",
        label: "Détail utilisateur",
        method: "GET",
        path: "/api/v{version}/admin/users/{userId}",
        description: "Retourne le profil complet d'un utilisateur.",
        auth: "admin",
        pathParams: [
          {
            key: "userId",
            label: "Guid utilisateur",
            sample: "00000000-0000-0000-0000-000000000000",
          },
        ],
        bodyMode: "none",
      },
      {
        id: "admin-user-status",
        label: "Activer / désactiver",
        method: "PUT",
        path: "/api/v{version}/admin/users/{userId}/status",
        description: "Change l'état actif / inactif.",
        auth: "admin",
        pathParams: [
          {
            key: "userId",
            label: "Guid utilisateur",
            sample: "00000000-0000-0000-0000-000000000000",
          },
        ],
        bodyMode: "json",
        body: {
          isActive: true,
        },
      },
      {
        id: "admin-login-history",
        label: "Historique de connexion",
        method: "GET",
        path: "/api/v{version}/admin/users/{userId}/login-history",
        description: "Pagine les connexions d'un utilisateur.",
        auth: "admin",
        pathParams: [
          {
            key: "userId",
            label: "Guid utilisateur",
            sample: "00000000-0000-0000-0000-000000000000",
          },
        ],
        query: {
          skip: 0,
          take: 20,
        },
        bodyMode: "none",
      },
      {
        id: "admin-api-keys",
        label: "Audit clés API",
        method: "GET",
        path: "/api/v{version}/admin/api-keys",
        description: "Filtre et consulte les clés API des utilisateurs.",
        auth: "admin",
        query: {
          search: "",
          userId: "",
          isActive: "",
          expired: "",
          skip: 0,
          take: 20,
        },
        bodyMode: "none",
      },
      {
        id: "admin-api-key-rotate",
        label: "Rotate clé API (admin)",
        method: "POST",
        path: "/api/v{version}/admin/api-keys/{apiKeyId}/rotate",
        description: "Régénère le secret d'une clé utilisateur.",
        auth: "admin",
        pathParams: [
          {
            key: "apiKeyId",
            label: "Guid clé API",
            sample: "00000000-0000-0000-0000-000000000000",
          },
        ],
        bodyMode: "none",
      },
      {
        id: "admin-api-key-revoke",
        label: "Révoquer clé API (admin)",
        method: "DELETE",
        path: "/api/v{version}/admin/api-keys/{apiKeyId}",
        description: "Révoque la clé ciblée côté admin.",
        auth: "admin",
        pathParams: [
          {
            key: "apiKeyId",
            label: "Guid clé API",
            sample: "00000000-0000-0000-0000-000000000000",
          },
        ],
        bodyMode: "none",
      },
      {
        id: "admin-user-revoke-keys",
        label: "Révoquer toutes les clés d'un user",
        method: "POST",
        path: "/api/v{version}/admin/users/{userId}/api-keys/revoke-all",
        description: "Révoque toutes les clés API liées à l'utilisateur.",
        auth: "admin",
        pathParams: [
          {
            key: "userId",
            label: "Guid utilisateur",
            sample: "00000000-0000-0000-0000-000000000000",
          },
        ],
        bodyMode: "none",
      },
      {
        id: "admin-audit-logs",
        label: "Audit logs",
        method: "GET",
        path: "/api/v{version}/admin/audit-logs",
        description: "Consulte les actions sensibles des administrateurs.",
        auth: "admin",
        query: {
          adminUserId: "",
          action: "",
          targetType: "",
          skip: 0,
          take: 20,
        },
        bodyMode: "none",
      },
    ],
  },
  {
    group: "Intégrations (API Key)",
    items: [
      {
        id: "integrations-ping",
        label: "Ping API Key",
        method: "GET",
        path: "/api/v{version}/integrations/ping",
        description: "Endpoint protégé par la politique ApiKeyOnly (en-tête X-API-Key).",
        auth: "apiKey",
        headers: [{ key: "X-API-Key", value: "{{apiKey}}" }],
        bodyMode: "none",
      },
    ],
  },
];
